### ISSUE TITLE
Import doesn't work

### ISSUE THREAD

**Issue by JosephArney566** [trynoice/android-app#1018]
### Description
Import brings up the file manager but doesn't allow me to select the json file

### To Reproduce
1. Go to Settings
2. Click on import from a file

### Screenshots
![Screenshot_20220611-161025](https://user-images.githubusercontent.com/107324076/173203397-53908daa-ce5d-40ed-8bc3-5ae85171faa3.png)

### Others
- Device: Amazon Fire Tablet 10 (2019)
- Android Version: Fire OS (Android 9.0 Pie) 
- App Version: 1.3.3 (Play Store)

**Comment by ashutoshgngwr** [comment]
Did you try to complete the action with a different file manager app?

**Comment by JosephArney** [comment]
> Did you try to complete the action with a different file manager app?

I installed MiX and that ended up working, must be the files app then 🤷

**Comment by ashutoshgngwr** [comment]
I'm glad it's working now. Thank you for using Noice!
