### ISSUE TITLE
Old sounds 

### ISSUE THREAD

**Issue by assolutooccidentale** [trynoice/android-app#1044]
Hi all
I've been using noice since my daughter was born.. Would it be possible to use the old sounds? They were less jumpy and better for my child...
Besides can there be a feature to download some of the sounds cause I happen to have no Internet at times?
Thank you

**Comment by ashutoshgngwr** [comment]
> They were less jumpy and better for my child

If you think there's a problem with any/all sounds, please add more details to the issue. e.g. Did you notice the jumpy effect in all sounds or a specific few? I also didn't quite understand what you meant by jumpy. A few more details here will help me in addressing this issue.

> Besides can there be a feature to download some of the sounds

I was supposed to do it two weeks ago, but I got caught up in some other stuff. I'll try to wrap it within the next few weeks.

> Would it be possible to use the old sounds?

Not with the recent version. You'll have to downgrade to 1.3.3. You can download the old APK [here](https://github.com/trynoice/android-app/releases/tag/1.3.3).

**Comment by assolutooccidentale** [comment]
> They were less jumpy and better for my child
>
> If you think there's a problem with any/all sounds, please add more
> details to the issue. e.g. Did you notice the jumpy effect in all sounds or
> a specific few? I also didn't quite understand what you meant by jumpy. A
> few more details here will help me in addressing this issue.
>
Old train or old cat purr were more plain, actual train goes from silence
to some screak sometimes, while cat purr is too loud if compared to the
other sounds



Besides can there be a feature to download some of the sounds
>
> I was supposed to do it two weeks ago, but I got caught up in some other
> stuff. I'll try to wrap it within the next few weeks.
>
> Would it be possible to use the old sounds?
>
> Not with the recent version. You'll have to downgrade to 1.3.3. You can
> download the old APK here
> <https://github.com/trynoice/android-app/releases/tag/1.3.3>.
>
Perfect: I'm afraid I'll stay with 1.3.3 for the time being

**Comment by ashutoshgngwr** [comment]
Thanks for the quick and detailed response. I'll try to fix/replace these sounds ASAP.

**Comment by ashutoshgngwr** [comment]
I've reverted both the sounds to their old samples. I hope this resolves the problems you've been facing with Noice. Thank you!
