### ISSUE TITLE
NonFree lib in F-Droid build

### ISSUE THREAD

**Issue by licaon-kter** [trynoice/android-app#1056]
`com.google.android.gms:play-services-oss-licenses` is not FOSS. See https://maven.google.com/com/google/android/gms/play-services-oss-licenses/17.0.0/play-services-oss-licenses-17.0.0.pom.

Could you please replace it with a FOSS alternative (see https://gitlab.com/-/snippets/1896503)? Thanks!

Ref: https://github.com/trynoice/android-app/commit/deb49114fdc40d83834d11fd62f2f23940668282

Ref: https://gitlab.com/fdroid/fdroiddata/-/jobs/2836572641#L1120

eg: https://github.com/nighthawk-apps/nighthawk-wallet-android/pull/129

**Comment by ashutoshgngwr** [comment]
Thanks for reporting it and suggesting potential alternatives, @licaon-kter. I'll make a patch release soon.
