### ISSUE TITLE
Only working with network connection

### ISSUE THREAD

**Issue by aproposnix** [trynoice/android-app#1072]
### Description
I've been using noice since the first version. It's been super noice to use :D 

Unfortunately, it now seems to only work when I am online. Last night I tried running it usng the same saved sound that i've been using for a long time. Within an hour it stopped playing the sound. When I got up to check the problem, I got a bunch of errors saying it couldn't connect to the internet.  If this is by design, it's a major disappointment.

### To Reproduce

1. Turn off all network connections
2. Start your sound (one that you saved already) 
3. Eventually, it will stop and complain about not being connected to the internet 

I'm using the latest version from F-Droid I tried going back to an older version but it seems all of the old version (1.x) have been removed from F-Droid.

**Comment by ashutoshgngwr** [comment]
Yes, I am sorry to disappoint you, but this is by design. I expanded the sound library (in terms of sound length) and it forced me to move it online.

Offline playback is only available if you subscribe to Noice Premium.

**Comment by ashutoshgngwr** [comment]
You can download older versions from GitHub releases. The latest one with full offline functionality is 1.3.3
