### ISSUE TITLE
Add reference

### ISSUE THREAD

**Issue by xmha97** [trynoice/android-app#1102]
Please add the sound reference:

![Screenshot_2022-11-26-01-46-24-302_com.github.ashutoshgngwr.noice.jpg](https://user-images.githubusercontent.com/23485114/204062030-69d2f289-e5b7-46e8-bcd0-6ac0b191ebbc.jpg)

**Comment by ashutoshgngwr** [comment]
@xmha97 We only disclose sources for assets whose license requires us to. Other than that, the sound library is a close-sourced component. Please let me know if there's anything else I can help you with!
