### ISSUE TITLE
App Crashes when Downloading Sounds

### ISSUE THREAD

**Issue by MattAKAFred** [trynoice/android-app#1205]
### Description
App crashes when downloading sounds on Pixel 7 GrapheneOS.

Not certain, but worth noting at no point does the app request any storage permissions, which may conflict with GrapheneOS storage restrictions.

### To Reproduce
1. Sign into premium account in GrapheneOS device
2. Select download icon next to any song
3. See error
4. Cannot open app without wiping storage
-->

### Others

- Device: Google Pixel 7
- Android Version: 14 (GrapheneOS)
- App Version: 2.5.6
- Downloaded From: Google Play

**Comment by ashutoshgngwr** [comment]
It has been resolved in https://github.com/trynoice/android-app/commit/079eb137f3c84a505e1ac90057ddb02a4d2b49ce, pending release. I'll try to push it out on the coming weekend; there are some Google Play compliance things I need to submit before I can publish an update.
