### ISSUE TITLE
Need translators for app localization

### ISSUE THREAD

**Issue by ashutoshgngwr** [trynoice/android-app#200]
Please refer to the [Weblate project](https://hosted.weblate.org/engage/noice/).

[![Translation status](https://hosted.weblate.org/widgets/noice/-/multi-auto.svg)](https://hosted.weblate.org/engage/noice/)

**Comment by ashutoshgngwr** [comment]
### Locale codes for Fastlane Metadata
 
> Copy pasted from Google Play Developers Console

Sometimes, these are in different format for Fastlane. Metadata should be at `./fastlane/metadata/android/<locale_code>/`

- Afrikaans – af
- Albanian – sq
- Amharic – am
- Arabic – ar
- Armenian – hy-AM
- Azerbaijani – az-AZ
- Bangla – bn-BD
- Basque – eu-ES
- Belarusian – be
- Bulgarian – bg
- Burmese – my-MM
- Catalan – ca
- Chinese (Hong Kong) – zh-HK
- Chinese (Simplified) – zh-CN
- Chinese (Traditional) – zh-TW
- Croatian – hr
- Czech – cs-CZ
- Danish – da-DK
- Dutch – nl-NL
- English (Australia) – en-AU
- English (Canada) – en-CA
- English (United Kingdom) – en-GB
- English – en-IN
- English – en-SG
- English – en-ZA
- Estonian – et
- Finnish – fi-FI
- French (Canada) – fr-CA
- French (France) – fr-FR
- Galician – gl-ES
- Georgian – ka-GE
- German – de-DE
- Greek – el-GR
- Gujarati – gu
- Hebrew – iw-IL
- Hindi – hi-IN
- Hungarian – hu-HU
- Icelandic – is-IS
- Indonesian – id
- Italian – it-IT
- Japanese – ja-JP
- Kannada – kn-IN
- Kazakh – kk
- Khmer – km-KH
- Korean – ko-KR
- Kyrgyz – ky-KG
- Lao – lo-LA
- Latvian – lv
- Lithuanian – lt
- Macedonian – mk-MK
- Malay (Malaysia) – ms-MY
- Malay – ms
- Malayalam – ml-IN
- Marathi – mr-IN
- Mongolian – mn-MN
- Nepali – ne-NP
- Norwegian – no-NO
- Persian – fa
- Persian – fa-AE
- Persian – fa-AF
- Persian – fa-IR
- Polish – pl-PL
- Portuguese (Brazil) – pt-BR
- Portuguese (Portugal) – pt-PT
- Punjabi – pa
- Romanian – ro
- Romansh – rm
- Russian – ru-RU
- Serbian – sr
- Sinhala – si-LK
- Slovak – sk
- Slovenian – sl
- Spanish (Latin America) – es-419
- Spanish (Spain) – es-ES
- Spanish (United States) – es-US
- Swahili – sw
- Swedish – sv-SE
- Tamil – ta-IN
- Telugu – te-IN
- Thai – th
- Turkish – tr-TR
- Ukrainian – uk
- Urdu – ur
- Vietnamese – vi
- Zulu – zu

**Comment by GriffinMLN** [comment]
Hey @ashutoshgngwr , want me to add Bulgarian translation?

**Comment by ashutoshgngwr** [comment]
@GriffinMLN yes please!

**Comment by lucastsantos** [comment]
I would like to help with pt-br translations 😄

**Comment by ashutoshgngwr** [comment]
@lucastsantos Please go ahead and create a PR! Ping me if you have any questions. :)

**Comment by VasilisKos** [comment]
Just started Greek translation. Probably will complete it today. 😉

**Comment by ashutoshgngwr** [comment]
@VasilisKos I am away for a while. Will probably review next week. Thank you for your contributions.

**Comment by VasilisKos** [comment]
> @VasilisKos I am away for a while. Will probably review next week. Thank you for your contributions.

No problem. Take care!

**Comment by franciscot** [comment]
I'm working with spanish too.

**Comment by VasilisKos** [comment]
How about adding in the credits of the app the translators too? That would be a least acknowledgment to their effort and contribution. ;)

**Comment by ashutoshgngwr** [comment]
@VasilisKos

It was there but I had to remove it because the list became too burdensome to maintain. See https://github.com/ashutoshgngwr/noice/commit/cd43a454694fa7da3baa542b8dc88b551c8bcf21

Now, the copyright mentions "the Noice Authors" instead of my name and there's another item below it to view the full list of the Noice Authors that points to the [GitHub contributors graph](https://github.com/ashutoshgngwr/noice/graphs/contributors).

![1](https://user-images.githubusercontent.com/7106123/115109251-436a1780-9f92-11eb-8501-63ef29026b7d.jpg)

**Comment by laralem** [comment]
@lucastsantos I'm already registered in Weblate site. I've added Portuguese (pt) language since it didn't existed yet (a bit different from pt-BR already translated, we usually have pt and pt-BR in interface translations to cover all Portuguese variants) and I was starting to translate when I saw the "save" button greyed out and the tool tip message:

> This translation only accept suggestions, and these are approved by voting.

I've already made a few translations in Weblate and this is the first time I saw this except in one situation: I only saw the "save" button greyed out in the past when I 'm not logged in Weblate by mistake. That's not this case.

**Comment by ashutoshgngwr** [comment]
Hi @laralem I manually review translations using Google Translate as a sanity check. You can add everything as suggestions and I'll review them ASAP.

**Comment by laralem** [comment]
@ashutoshgngwr thanks. Although unusual I will do that.

**Comment by laralem** [comment]
@ashutoshgngwr I've finished the translations suggestions in Portuguese (pt). 

Some words are not easy to translate and understand to end users, for example "Presets" could be changed in original English strings to "Sound mixes" or just "Mixes" if don't fit in screen, as are they called in one introduction text.

**Comment by ashutoshgngwr** [comment]
Thanks @laralem I'll review them ASAP

**Comment by chihung93** [comment]
I would like to help with `vi` translations. is it okay?

**Comment by ashutoshgngwr** [comment]
@chihung93 Yes, but please use [Weblate](https://hosted.weblate.org/projects/noice/android/vi/) for adding translations.

**Comment by ashutoshgngwr** [comment]
@chihung93 If you want to participate in the Hacktober Fest 2021, you can directly create a PR here on GitHub. I don't think changes from Weblate will count as participation.

**Comment by chihung93** [comment]
@ashutoshgngwr : I have added it and created a PR 
https://github.com/ashutoshgngwr/noice/pull/834

**Comment by ashutoshgngwr** [comment]
Okay! Please do not translate anything from [`donottranslate.xml`](https://github.com/ashutoshgngwr/noice/blob/main/app/src/main/res/values/donottranslate.xml).
