### ISSUE TITLE
Adding Pomodoro technique to Noice

### ISSUE THREAD

**Issue by sabo3** [trynoice/android-app#443]
It would be nice to see a pomodoro technique mode built in this app, in a similar way to how that [Tide](https://play.google.com/store/apps/details?id=io.moreless.tide) app works.

**Comment by ashutoshgngwr** [comment]
Thanks for the suggestion. I'll check this.

**Comment by ashutoshgngwr** [comment]
There's little to no traction over this feature. I'm closing this as not-planned for now.
