### ISSUE TITLE
Enhancement: the rain sounds are too shrill/crispy. Add a soft versions of the rain sounds

### ISSUE THREAD

**Issue by ghost** [trynoice/android-app#605]
### Description
The rain sounds are too crispy and this can be stressful instead of relaxing. I believe that this crispness is because the rain is falling into impermeable surfaces like concrete. The sound of rain that falls into earth or plants is softer. 

The current rain sounds worse my tinnitus, so this might happen with other people that have this condition, but I can speak for everyone.

### To Reproduce
Play any rain sound. The "intense rain" has this problem more prominent. 

### Others
- Device: Galaxy A50
- Android Version: 11
- App Version: 0.16.0

**Comment by ashutoshgngwr** [comment]
@blackandyellowgecko I have changed rain sound samples so many times that I am honestly tired of it. xD If you want something better, please find it on BBC Sound effects (see #361) or [FreeSound](https://freesound.org) and tell me. I'll see if I can replace the current samples with it.

**Comment by blackandyellowgecko** [comment]
okay! I'll do this o/

**Comment by yashashebbarabailu** [comment]
Can we add audio effect chain? High cut eq filter should work in this case. This may be overdoing it. But will be helpful to customize sound as needed without changing the sample.

Found repos that maybe helpful
- [gregnr/AudioEffects](https://github.com/gregnr/AudioEffects)
- [xeinebiu/android_audioeffects](https://github.com/xeinebiu/android_audioeffects)

**Comment by ashutoshgngwr** [comment]
I'd ask if this is still an issue in v2, but I suppose that's impossible. If someone is watching this issue and feels that it is unresolved in v2, please open a new issue.
