### ISSUE TITLE
Start looping sounds at random offset

### ISSUE THREAD

**Issue by jfitie** [trynoice/android-app#622]
### Is your feature request related to a problem? Please describe.
1) Starting a looping sound always starts it at the beginning of the file, making it sound repetitive. Reproduce by stopping/starting a looping sound multiple times; f.ex. Coffee shop.
2) The same is true for non-looping sounds, especially in presets, they all start at the beginning and at the same time when starting the preset.

### Describe the solution you'd like
1) When a looping sound is started, do not start at the beginning of the sound file, but at a random offset in the sample.
2) A non-looping sound is followed by a delay with a set duration between 30 seconds and 30 minutes. This order could be reversed, so first the delay and then the sound. This way, non-looping sounds will not all start at the same time when starting the preset. For the first delay, the delay could be a random delay between 0 and the delay set for the sound.

**Comment by ashutoshgngwr** [comment]
This is an implicit feature of the v2 sound engine. The v2 sound engine divides a sound into several independent segments and it selects a random segment when the sound starts playing.
