### ISSUE TITLE
recurring wake-up timer/alarm

### ISSUE THREAD

**Issue by ghost** [trynoice/android-app#629]
### Ist est related to a problem? Please describe.
I'd like to use noice as an alarm, because nature sounds are the only ones that don't force to wake me up all moody, and being able to set up custom mix of sounds is awesome. Current wake up timer is a one time thing, or at least that seems to be the case, and I'm not fool-proof, so I might forget one day to set the alarm.

### Describe the solution you'd like
Add a check mark when setting an alarm to add as a permanent alarm, and maybe add a new tab (sort of like the tab for sounds presets) where you can see all of the alarms you have configured so far. Maybe a toggle for each alarm to deactivate/activate quickly? Even a full fledged alarm-like features like toggling alarms for certains days of the week or what not.

But simply a daily wake up timer would be more than enough for now.

Sorry if this was not the intent for your app, but I haven't been able to find foss alternatives apps for this purpose. Thanks :)

**Comment by ashutoshgngwr** [comment]
Hey @maguilara The current wake-up timer was a pilot feature. I am planning to make it a full-fledged alarm clock, but I am not sure about the timeline.

**Comment by maguilara** [comment]
Good to know you have thought about, it has so much potential. Thanks for the app!

**Comment by lanmarc77** [comment]
May I add the following idea/feature which fits to this topic.
A two staged timer/alarm.

Stage two works like the alarm right now. On a specific time (in the future with a weekly schedule) a specific sound is enabled.
Stage one is enabled earlier than stage two. How much earlier can be setup within a minutes range. Additionally stage one has a linear volume increase slider and a maximum ring time. When stage one is fired the alarm is playing the setup sound and increases slowly (based on thes volume increse slider and a max/min setting) the volume. The volume is increased until the maximum set volume and only sonds as long as the maximum ring time says.
This allows for [sleep cycle](https://www.healthline.com/health/healthy-sleep/90-minute-sleep-hack) aware wakeup and would be a unique feature in fdroid. I currently use [Gentle Alarm](https://play.google.com/store/apps/details?id=com.mobitobi.android.gentlealarmwidget&hl=gsw&gl=US) which seems abondend. It is one of my last non open source apps.
And thank you for this app as well!

**Comment by ashutoshgngwr** [comment]
@lanmarc77 Thanks for the suggestion! I'll keep it in consideration when I start reimplementing the alarm feature.
