### ISSUE TITLE
Sleep timer already has large time set, needing reset

### ISSUE THREAD

**Issue by rancidfrog** [trynoice/android-app#816]
Sometimes when clicking on sleep timer it has already set time usually long:
![](https://i.imgur.com/qB6pRY4.jpg)

Not sure why, as it happens randomly. 
Also, happens on  1.3.3

**Comment by ashutoshgngwr** [comment]
It's unlikely for me to fix it anytime soon. The timer and alarm features are due for a makeover with support for managing multiple items at a time. I'll get to it after the core changes that are planned for v2.

**Comment by rancidfrog** [comment]
Yes,
I just wanted to note down this curious issue as it happened before, in previous versions I believe and remains in latest release.
Just an annoyance as you have to click reset then set time.
Do you know the cause, though?
I usually set a sleep timer and it finishes.
Then on next use I select a preset, sometimes a different preset, but in most cases whenever I set a timer, the preset is played until timer ends.
I will try to find out when it occurs

**Comment by ashutoshgngwr** [comment]
The sleep timer currently uses the uptime clock (relative to boot-time). It also persists the timer on storage, so it can correctly display the timer UI. My theory is that on rebooting the device, Noice picks the persisted timer as ongoing and displays it. I will fix it ASAP, but I won't be able to release it until a few weeks.

https://github.com/ashutoshgngwr/noice/blob/85a9d9b18bd926fa19e315ea66f71c5c4c9436c1/app/src/main/java/com/github/ashutoshgngwr/noice/playback/PlaybackController.kt#L292-L326

**Comment by ashutoshgngwr** [comment]
I've fixed this issue and it should be resolved in the next release.
