### ISSUE TITLE
Add wavy brown+pink noise

### ISSUE THREAD

**Issue by Rult** [trynoice/android-app#842]
Personally, I like the monotonous brown noise, but for sleeping it's better to listen to its [wavy version](https://github.com/ashutoshgngwr/noice/files/7447955/sox-waves-edit2.zip). Regular crashing waves are too crispy.

If you'd like to generate it (as the other raw noises) instead of re-using the sample, you need to use [SoX](http://sox.sourceforge.net/).
After installed, it's played with this command:
`play -n synth brownnoise synth pinknoise mix synth 0 0 0 10 10 40 trapezium amod 0.1 30`
Or recorded with this:
`sox -n -r 44100 output.wav synth 60 brownnoise synth 60 pinknoise mix synth 0 0 0 10 10 40 trapezium amod 0.1 30`
(where `60` is length in seconds, it's better to generate initially in wav, then to mp3 via ffmpeg)

Originally the command was written on [AskUbuntu](https://askubuntu.com/questions/789465/generate-white-noise-to-calm-a-baby/789472#comment1296847_789472).
```
The longer period [10 seconds] makes it harder to notice the regularity. 
The numbers mean: 
0.1 = wave crash frequency (0.1 Hz = one wave every 10 seconds); 
30% = noise level in between waves; 
1st 10% = duration (over the 10 seconds) of the rising part of the wave; 
2nd 10% = when it starts falling 
(they are both 10% so that the wave crashes as soon as it's done rising in volume); 
40% duration of the entire wave: 
this means 100% - 40% = 60% of the time is spent waiting between waves.
– Tobia
```

The reason I'd like to see this in Noice is because the app provides smooth turn-off when the timer goes off, which can't be achieved as easily with just SoX.

**Comment by ashutoshgngwr** [comment]
bump
