### ISSUE TITLE
Paused audio after pausing while the audio is fading

### ISSUE THREAD

**Issue by FabianPaci** [trynoice/android-app#977]
### Description
I havnt taken the time to look at the repo yet, so correct me if this is known un-documented issue or something. Basically, when you pause your sounds using the pause/play button located at the top right and play your sounds again quickly after pasuing the sounds will remain in a pause-like state -
not producing any sounds.

### To Reproduce
Steps:
1. Play some sounds
2. Pause the sounds using the pause/play button
3. Play the sounds again quickly after pausing them (while the audio is still fading out)

Result: no audio even when being played

### Screenshots
N/A

### Others
- Device: Samsung galaxy s8
- Android Version: 9
- App Version: 1.3.3 (F-Droid)

**Comment by ashutoshgngwr** [comment]
Yeah, I am aware of this issue. I am rewriting the sound engine for [v2](https://trynoice.com/news/v2-announcement) as we speak. This should be fixed in the next release.

**Comment by FabianPaci** [comment]
Awesome, thanks so much for this amazing app!

**Comment by FabianPaci** [comment]
(sorry to reopen this issue but i didnt want to open a new issue for something that could just be simply answered) Is the sleep timer still counting down when paused also getting fixed in V2?

**Comment by ashutoshgngwr** [comment]
After recieving feedback, I had planned to tightly couple sleep timers (allow multiple) with presets. This issue was unnoticed until now. I'll fix it as well. Although, I won't be able to do it in the initial release; maybe in a couple of releases down the line. It can be a while before that happens.

On a side note, please keep this issue open so it's easier to track.

**Comment by ashutoshgngwr** [comment]
The original issue is fixed in the main branch. I'll be releasing its beta on the Play Store very soon. The sleep timer issue is still unresolved. Please subscribe to #1016 for updates.
